In [2]:
import torch as t

x = t.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [8]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
t.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
t.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [3]:
t.randn(2,3)

tensor([[-0.1124, -0.2551, -0.2665],
        [ 1.4429,  1.8619, -1.2579]])

In [11]:
a = t.tensor([1.0,2,4,8])
b = t.tensor([2,2,2,2])
# ** 幂运算
a+b,a-b,a*b,a/b,a**b

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
# e**x
t.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [16]:
x = t.arange(12, dtype=t.float32).reshape(3, 4)
y = t.randn(3, 4)
x, y
t.cat((x, y), dim=0), t.cat((x, y), dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.6248, -0.2561, -1.3332, -0.1447],
         [ 0.0251, -0.3278, -0.1704,  0.5581],
         [-1.2739, -0.7365, -1.9925, -0.7892]]))

In [18]:
x == y
x.sum()

tensor(66.)

In [23]:
# 广播机制
a = t.arange(3).reshape(3, 1)
b = t.arange(2).reshape(1, 2)
a, b
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
x = t.arange(12).reshape(3, 4)
x,x[-1],x[-1,:]
x,x[::2,::2]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  2],
         [ 8, 10]]))

In [37]:
# 节省内存
x, y
before = id(y)
y = y + x
before, id(y), before == id(y)


(140345612683648, 140345671129280, False)

In [43]:
# 原地操作
z = t.zeros_like(x)
print(id(z))
print(id(y))
z[:] = x+y
y += y
print(id(y))
print(id(z))


140345671187264
140345671129280
140345671129280
140345671187264


In [46]:
# 转换为其他python对象

a = t.tensor(3)
a,a.item(),float(a),int(a)

(tensor(3), 3, 3.0, 3)

In [53]:
import os
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
data_file

with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [54]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [58]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs, outputs
inputs = inputs.fillna(inputs.mean())
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs


/var/folders/kd/f5tkm9sd4qdbr32gk6yqjh2m0000gn/T/ipykernel_5187/1276834610.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs=inputs.fillna(inputs.mean())


NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [59]:
x, y = t.tensor(inputs.values), t.tensor(outputs.values)
x, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [61]:
# 线性代数

x = t.arange(4)
x[2]

tensor(2)

In [9]:
import requests

a = 'https://btsstatic.oss-cn-shanghai.aliyuncs.com/admin/emoji/'
c = '.gif'
base = '/Users/changjiexian/Downloads/project/pybbs/src/main/resources/static/gif/'
pic_url = a+str(104)+c
base_url = base+str(104)+c
r = requests.get(pic_url)
with open(base_url, "wb")as f:
    f.write(r.content)
    

In [19]:
import torch as t
from torchvision import transforms

to_tensor = transforms.ToTensor()



Type:        module
String form: <module 'torchvision.transforms' from '/opt/miniconda3/lib/python3.8/site-packages/torchvision/transforms/__init__.py'>
File:        /opt/miniconda3/lib/python3.8/site-packages/torchvision/transforms/__init__.py
Source:     
from .transforms import *
from .autoaugment import *
